import os

DEBUG = True

USER = 'root'
PASSWORD = 'root'
HOST = '127.0.0.1'
PORT = '3306'
DATABASE = 'zlbbs'

DB_URI = 'mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8'.format(USER, PASSWORD, HOST, PORT, DATABASE)

SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = False

SECRET_KEY = os.urandom(24)

CMS_USER_ID = 'FHEUWIFHJKS'
FRONT_USER_ID = 'UIDOWHCI3892J'


MAIL_SERVER = 'smtp.qq.com'
MAIL_PORT = '587'
MAIL_USE_TLS = True
MAIL_USERNAME = '2026737105@qq.com'
MAIL_PASSWORD = 'bjehpsjpfixhbege'
MAIL_DEFAULT_SENDER = '2026737105@qq.com'


ALIDAYU_APP_KEY = ''
ALIDAYU_APP_SECRET = ''
ALIDAYU_SIGN_NAME = ''
ALIDAYU_TEMPLATE_CODE = ''



UEDITOR_UPLOAD_PATH = os.path.join(os.path.dirname(__file__), 'images')
UEDITOR_UPLOAD_TO_QINIU = False
UEDITOR_QINIU_ACCESS_KEY = ""
UEDITOR_QINIU_SECRET_KEY = ""
UEDITOR_QINIU_BUCKET_NAME = ""
UEDITOR_QINIU_DOMAIN = ""


PER_PAGE = 10


CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'