"""empty message

Revision ID: 329bb8fb13ab
Revises: 2562f0a16068
Create Date: 2019-08-01 11:16:20.797041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329bb8fb13ab'
down_revision = '2562f0a16068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highlight_post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('highlight_post')
    # ### end Alembic commands ###
