"""empty message

Revision ID: a174cdff5cea
Revises: 329bb8fb13ab
Create Date: 2019-09-17 15:35:04.691179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a174cdff5cea'
down_revision = '329bb8fb13ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('read_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'read_count')
    # ### end Alembic commands ###
